name: Solidity CI

on:
  push:
    branches: [profit-engine-v07]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  forge-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Build
        run: forge build
